export const BAIRROS: string[] = [
  "Antares",
  "Barro Duro",
  "Bebedouro",
  "Benedito Bentes",
  "Bom Parto",
  "Canaã",
  "Centro",
  "Chã da Jaqueira",
  "Chã de Bebedouro",
  "Cidade Universitária",
  "Clima Bom",
  "Cruz das Almas",
  "Farol",
  "Feitosa",
  "Fernão Velho",
  "Garça Torta",
  "Gruta de Lourdes",
  "Guaxuma",
  "Ipioca",
  "Jacarecica",
  "Jacintinho",
  "Jaraguá",
  "Jardim Petrópolis",
  "Jatiúca",
  "Levada",
  "Mangabeiras",
  "Martins",
  "Mutange",
  "Ouro Preto",
  "Pajuçara",
  "Petrópolis",
  "Pinheiro",
  "Pitanguinha",
  "Ponta da Terra",
  "Ponta Grossa",
  "Ponta Verde",
  "Pontal da Barra",
  "Poço",
  "Prado",
  "Riacho Doce",
  "Rio Novo",
  "Santa Amélia",
  "Santa Lúcia",
  "Santo Amaro",
  "Santos Dumont",
  "São Jorge",
  "Serraria",
  "Tabuleiro do Martins",
  "Trapiche da Barra",
  "Vergel do Lago",
  "Vila Brejal"
];
